const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.join(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const manifestSource = read("assets/v99/mascot-manifest-v99.js");
const renderer = read("assets/v99/vduckie-mascot-v99.js");
const css = read("assets/v99/vduckie-lv7-lv8-v99.css");
const developer = read("assets/v99/developer-preview-v99.js");
const thoughts = read("assets/v95/thoughts-v95.js");
const index = read("index.html") + "\n" + read("app-shell-v88.html");
function baseManifest() { const levels = {}; for (let level = 1; level <= 10; level += 1) levels[level] = Object.freeze({ level, defaultAsset: `before-${level}.webp`, renderMode: level <= 6 ? "sprite" : "full-skin" }); return Object.freeze({ version: "98.0", states: Object.freeze(["idle", "hover", "tap", "success", "sad", "outfit-change", "outfit-confirm", "level-up", "hatching", "glow"]), renderModes: Object.freeze(["full-skin", "sprite"]), levels: Object.freeze(levels), items: Object.freeze({}), defaults: Object.freeze({ outfit: "stage-default", accessory: "none" }), categories: Object.freeze([]), variants: Object.freeze([]), motion: Object.freeze({}), eggAssets: Object.freeze({}), level2Sprite: Object.freeze({}), levelSprites: Object.freeze({}), resolve(query) { return Object.freeze({ level: Number(query.level), asset: `before-${query.level}.webp` }); }, getItems() { return []; }, getItem() { return null; } }); }
test("Level 7-8 map to new nine-frame WebP sprites and preserve Level 1-6", () => { const window = { VDuckieMascotManifest: baseManifest() }; vm.runInContext(manifestSource, vm.createContext({ window, Object, Array, Number, String, Math })); const manifest = window.VDuckieMascotManifest; assert.equal(manifest.version, "99.0"); assert.equal(manifest.resolve({ level: 7, state: "hover" }).frames, 9); assert.equal(manifest.resolve({ level: 8, state: "sad" }).frames, 9); assert.match(manifest.getLevel(7).defaultAsset, /lv7\/expert-sprite\.webp/); assert.match(manifest.getLevel(8).defaultAsset, /lv8\/leader-sprite\.webp/); assert.equal(manifest.getLevel(6).defaultAsset, "before-6.webp"); assert.ok(fs.statSync(path.join(root, "assets/vduckie/lv7/expert-sprite.webp")).size > 10000); assert.ok(fs.statSync(path.join(root, "assets/vduckie/lv8/leader-sprite.webp")).size > 10000); });
test("Level 7-8 interactions use real frames with badge glow and reduced motion", () => { for (const name of ["v99-lv7-idle", "v99-lv7-hover", "v99-lv7-success", "v99-lv7-sad", "v99-lv7-outfit", "v99-lv8-idle", "v99-lv8-hover", "v99-lv8-success", "v99-lv8-sad", "v99-lv8-outfit"]) assert.match(css, new RegExp(name)); assert.match(css, /v99-badge-glow/); assert.match(css, /prefers-reduced-motion:reduce/); assert.match(renderer, /v99-character-sprite/); assert.doesNotMatch(renderer + css, /glasses-layer|accessory-front-layer|outfit-layer/); });
test("Level 7-8 thoughts are centralized, bilingual and non-repeating", () => { const window = {}; vm.runInContext(thoughts, vm.createContext({ window, Object, Array, Number, Math })); for (const level of [7, 8]) { const list = window.VDuckieThoughts.list(level); assert.ok(list.length >= 10); list.forEach(item => { assert.ok(item.zh.trim()); assert.ok(item.vi.trim()); }); assert.notEqual(window.VDuckieThoughts.next(level).id, window.VDuckieThoughts.next(level).id); } assert.match(thoughts, /先分析原因，再给方案/); assert.match(thoughts, /团队需要清楚的优先级/); });
test("Developer Preview covers Level 7-8 states without EXP writes", () => { for (const state of ["idle", "hover", "tap", "success", "sad", "outfit-change"]) assert.match(developer, new RegExp(`"${state}"`)); assert.match(developer, /bridge\.enable\(Number\(level\)\)/); assert.doesNotMatch(developer, /awardEXP|total_exp|Supabase|streak/i); });
test("V99 production order uses relative paths only", () => { assert.match(index, /mascot-manifest-v98\.js\?v=98\.0[^\n]+mascot-manifest-v99\.js\?v=99\.0[^\n]+vduckie-mascot-v95\.js/); assert.match(index, /vduckie-mascot-v98\.js\?v=100\.0[^\n]+vduckie-mascot-v99\.js\?v=100\.0[^\n]+customization-store-v94\.js/); assert.match(index, /vduckie-lv7-lv8-v99\.css\?v=99\.0/); assert.match(index, /developer-control-center\.js\?v=108\.1/); assert.doesNotMatch(manifestSource + renderer + index, /https:\/\/vduckie\.pages\.dev/); });
